project:
  type: website
website:
  title: "Richa Anghan"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "About"
        file: about.qmd
    right:
      - icon: github
        href: https://github.com/richa1623
format:
  html:
    theme: flatly
    css: styles.css



